---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: "11.4.4"

suites:
- name: default
  run_list:
  - "recipe[chef-solo-search]"
  - "recipe[wal-e_test::default]"
  - "recipe[minitest-handler]"
  attributes: {}

- name: encrypted_data_bag
  run_list:
  - "recipe[chef-solo-search]"
  - "recipe[wal-e_test::encrypted_data_bag]"
  - "recipe[minitest-handler]"
  attributes:
    wal-e:
      s3:
        data_bag_item: "wal_e_encrypted"
      use_encrypted_data_bag: true
  encrypted_data_bag_secret_key_path: "test/data_bag_secret"
