---
driver:
  name: docker
  use_sudo: false
  require_chef_omnibus: "latest"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
    - "recipe[wal-e::default]"
