language: ruby
cache:
  bundler: true
  directories:
  - ../vendor/bundle
  - vendor/cookbooks
sudo: false
bundler_args: --without integration --path=$PWD/../vendor/bundle
rvm:
  - 2.2
  - 2.3
before_script:
  - bundle exec berks vendor vendor/cookbooks
script:
  - bundle exec strainer test
